version: 2.1

jobs:
  build-and-test:
      docker:
        - image: circleci/node:13
          steps:
            - checkout
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test