version: 2.1

jobs:
  build:
      docker:
        - image: circleci/node:13
          steps:
            - checkout
            - run: npm install
            - run: npm test
workflows:
    build:
      jobs:
        - build